---
title: "Final"
author: "Miguel Angel Malagon - Manuel Camilo Corredor"
date: '2022-05-21'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Measuring fund performance

Librerias
```{r,echo=FALSE, warning=FALSE}
#install.packages("quantmod")
library(quantmod)
library(readxl)
library(dygraphs)
library(PerformanceAnalytics) #for sharpe
library(datasets)
library(tidyverse) #for sort
#install.packages("kableExtra")
#library(kableExtra)
```

Lista de activos
```{r}
tickers <- c("VSMPX","VFIAX","DODGX","SWPPX","RLBGX","FSGEX","VGHAX",
             "FPCIX","FTBFX","BBCPX","PTTRX","FKINX","CAIBX","ABALX",
             "AGTHX","GFFFX","AMECX","TRBCX","PIMIX","FBKWX")


```

Precio de los activos y rentabilidades
```{r,echo=FALSE}
Prices <- c()
for (activos in tickers){
  Prices <- cbind(Prices,getSymbols.yahoo(
    Symbols =activos,index.class  = 'Date',from ="2017-05-01",
    to="2022-03-02",periodicity = "monthly",auto.assign = FALSE)[,6])
}
colnames(Prices)<-tickers

```

```{r}
Rentabilidad <- c()
n <- ncol(Prices)
for (i in 1:n){

    Rentabilidad <- cbind(Rentabilidad,monthlyReturn(Prices[,i],leading = FALSE))[-1,]
}
colnames(Rentabilidad)<-tickers  
#mean(Rentabilidad[,1:20]) crear rentabilidad 
```

```{r}
promedio <- cbind()
x <- ncol(Rentabilidad)
for (i in 1:x) {
  promedio<- cbind(promedio,mean(Rentabilidad[,i]))
}
```


```{r}
sharpe_ratio <- round(
  SharpeRatio(Rentabilidad, Rf = 0.0016761), 4
)
#?SharpeRatio
# filtrar

Filtro <- cbind(sort(sharpe_ratio[1,1:20]))
print(Filtro[16:20,1])
#Filtro <- as.matrix(sort(Filtro,decreasing = TRUE))
#head(Filtro)
```

$$
\frac{\overline{(R_{a}-R_{f})}}{√{σ_{(R_{a}-R_{f})}}}
$$


```{r}
#kable(Prices)
#kable(Rentabilidad
#      )
```

```{r}
# FAMA & FRENCH
Data_Factors <- read_excel("Data_Factors.xlsx")
names(Data_Factors)[2] <-"RMRF"
```


```{r}
#CALCULAMOS LAS VARIABLES Y (Rentabilidad_activo - RF)
variable_y <- c()
x <- ncol(Rentabilidad)
for (i in 1:x) {
  variable_y<- cbind(variable_y,((Rentabilidad[,i])-(Data_Factors$RF)))
}
```


```{r}
#creo que no es necesario
#Data_Regression <- merge(x=Data_Factors,y=variable_y,by =NULL)
Data_Regression <- cbind(Data_Factors[,2:5],variable_y)

```

$$
R_{it}=\alpha_i+\beta \ast RMRF_t +b_i \ast SMB_t +h_i \ast HML_t + \epsilon_{it}
$$

```{r}
#Preparamos la Regresión


regression <- lm(VSMPX ~ RMRF + SMB + HML, data = Data_Regression)
#summary(regression)
coefficients(regression)
# NOTA: Falta hacer un for que haga cada regresion cambiando el activo y lo coloque en un dataframe

```


```{r}
X1 <- Data_Factors[,2:4]
X <- as.matrix( cbind(1,X1))
Y <- as.matrix(variable_y[,1])
beta <- solve(t(X)%*%X)%*%t(X)%*%Y
beta

```

$$
\hat{\beta}=(X^TX)^{-1}X^TY
$$

```{r}
betas <- cbind()
Intercepto <- cbind()
RMRF <- cbind()
SMB <- cbind()
HML <- cbind()
for (i in 1:20){
  betas <- solve(t(X)%*%X)%*%t(X)%*%variable_y[,i]
  Intercepto[i] <- betas[1,1]
  RMRF[i]<- betas[2,1]
  SMB[i] <- betas[3,1]
  HML[i] <- betas[4,1]
}
```

```{r}
todo <- cbind(Intercepto,RMRF,SMB,HML)
# Transpone todas las columnas menos la primer
df_transpose <- data.frame(t(todo))
# Añadimos los nombres de las columnas
colnames(df_transpose)<-tickers
```

```{r}
Filtro1 <- cbind(sort(df_transpose[1,1:20]))
Filtro2 <- t(Filtro1)
print(Filtro2[16:20,1])
```




# Punto 2

```{r}
library(readxl)
Betas <- read_excel("Betas.xlsx")
View(Betas)
```

```{r}
Rm <-Betas$`Adj Close**`
Raapl <- Betas$`Adj Close`
Var1 <- c()
Var2 <- c()
n <- length(Rm)
for(i in 1:n){
Var1[i] <- (Rm[i+1]/Rm[i])-1
Var2[i] <- (Raapl[i+1]-Raapl[i])/Raapl[i]

}
Var1 <- c(NA,Var1)
Var1 <-Var1[-269]
Var2<- c(NA,Var2)
Var2 <-Var2[-269]

Data_Betas <- as.data.frame(cbind(Raapl,Var2,Rm,Var1)[-1,])
#Data_Betas <- cbind(Data_Betas)
```

```{r}

cov <- cov(Data_Betas$Var2,Data_Betas$Var1)
var <- var(Data_Betas$Var1)

beta <- cov/var
t <- dim(Data_Betas)[1]
ventana <- cbind()
cov1 <- cbind()
var1 <- cbind()



#for (i in 10:(t-10)) {
#cov1 <- xxx[1:i,]

#}




for(i in 1:(n-60)){
  cov1[i] <- cov(Data_Betas$Var2[i:(59+i)],Data_Betas$Var1[i:(59+i)])
  var1[i] <- var(Data_Betas$Var1[i:(59+i)])
  ventana <- cov1/var1
}
y <- 1:208
ventana1 <- as.data.frame(cbind(ventana,y)) 

plot(ventana)






ggplot(ventana1,(aes(y=ventana,x=y)))+
geom_line()






```

```{r}
library(ggplot2)
geom_line(aes(x=ventana))
```
